import { test } from "node:test";
import assert from "node:assert/strict";
import { writeFile, mkdir, readFile, rm } from "node:fs/promises";
import { join } from "node:path";
import { writeV5Report } from "../report/writeV5Report.js";
import type { NormalizedPromptfooResult } from "../promptfoo/normalizePromptfooResults.js";
import { assessGovernance } from "../report/analyzePromptChange.js";

function makeResult(testId: string, score: number, pass: boolean, assertions: Array<{ type: string; pass: boolean; score: number; reason: string; metric?: string }> = []): NormalizedPromptfooResult {
  return { testId, userInput: `input for ${testId}`, output: `output for ${testId}`, score, pass, assertions: assertions.length > 0 ? assertions : [{ type: "llm-rubric", pass, score, reason: pass ? "passed" : "failed" }] };
}

test("V5 Report: generates v5-report.md with all 12 sections", async () => {
  const tmpDir = join(process.cwd(), "tmp-v5-report-test");
  await mkdir(tmpDir, { recursive: true });
  const baselineResults: NormalizedPromptfooResult[] = [makeResult("t1", 60, false), makeResult("t2", 70, true)];
  const bestResults: NormalizedPromptfooResult[] = [makeResult("t1", 85, true), makeResult("t2", 80, true)];
  const governance = assessGovernance({ baseline: baselineResults, candidate: bestResults, originalPrompt: "test", candidatePrompt: "test improved", goalProfile: { detectedCapabilities: ["advice"], detectedForbiddenActions: ["no refund"], detectedRiskTypes: ["privacy"] } });
  await writeV5Report({ runDir: tmpDir, projectName: "test", promptfooVersion: "0.105.0", targetProviderModel: "deepseek", graderProviderModel: "deepseek", testGeneratorSource: "promptfoo-dataset", sameModelGrader: true, hasAutoGeneratedTests: true, baselinePublicResults: baselineResults, bestPublicResults: bestResults, governance, ledger: [{ iteration: 0, promptVersion: "baseline", status: "baseline", score: 65, passRate: 0.5, passed: 1, failed: 1, summary: "init" }], originalPrompt: "test", bestPrompt: "test improved", finalVerdictLabel: "accepted", finalVerdictReasons: ["ok"], humanReviewRequired: true, runtimeStats: { totalApiCalls: 10, totalLatencyMs: 5000, cacheHits: 3, retryErrors: 1, errorCount: 0 }, optimizeCalls: 1, optimizeCommand: "npx promptfoo optimize", validationSplit: 0.2 });
  const report = await readFile(join(tmpDir, "v5-report.md"), "utf-8");
  assert.ok(report.includes("## 1."), "Section 1 missing");
  assert.ok(report.includes("## 2."), "Section 2 missing");
  assert.ok(report.includes("## 3."), "Section 3 missing");
  assert.ok(report.includes("## 4."), "Section 4 missing");
  assert.ok(report.includes("## 5."), "Section 5 missing");
  assert.ok(report.includes("## 6."), "Section 6 missing");
  assert.ok(report.includes("## 7."), "Section 7 missing");
  assert.ok(report.includes("## 8."), "Section 8 missing");
  assert.ok(report.includes("## 9."), "Section 9 missing");
  assert.ok(report.includes("## 10."), "Section 10 missing");
  assert.ok(report.includes("## 11."), "Section 11 missing");
  assert.ok(report.includes("## 12."), "Section 12 missing");
  await rm(tmpDir, { recursive: true, force: true });
});

test("V5 Report: handles empty results", async () => {
  const tmpDir = join(process.cwd(), "tmp-v5-report-empty");
  await mkdir(tmpDir, { recursive: true });
  const governance = assessGovernance({ baseline: [], candidate: [], originalPrompt: "test", candidatePrompt: "test", goalProfile: { detectedCapabilities: [], detectedForbiddenActions: [], detectedRiskTypes: [] } });
  await writeV5Report({ runDir: tmpDir, projectName: "empty", promptfooVersion: "0.105.0", targetProviderModel: "m", graderProviderModel: "m", testGeneratorSource: "manual", sameModelGrader: false, hasAutoGeneratedTests: false, baselinePublicResults: [], bestPublicResults: [], governance, ledger: [], originalPrompt: "test", bestPrompt: "test", finalVerdictLabel: "needs_review", finalVerdictReasons: [], humanReviewRequired: false });
  const report = await readFile(join(tmpDir, "v5-report.md"), "utf-8");
  assert.ok(report.length > 0, "Report should not be empty");
  await rm(tmpDir, { recursive: true, force: true });
});