/**
 * V5 Report Generator
 *
 * Generates v5-report.md with 12 Chinese sections.
 */

import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { LedgerEntry, ReleaseDecision } from "../types.js";
import type { GovernanceAssessment } from "./analyzePromptChange.js";
import type { NormalizedPromptfooResult } from "../promptfoo/normalizePromptfooResults.js";
import { summarizeMetricResults } from "../promptfoo/assertions.js";

export interface V5ReportInput {
  runDir: string;
  projectName: string;
  promptfooVersion: string;
  targetProviderModel: string;
  graderProviderModel: string;
  testGeneratorSource: string;
  sameModelGrader: boolean;
  hasAutoGeneratedTests: boolean;
  baselinePublicResults: NormalizedPromptfooResult[];
  bestPublicResults: NormalizedPromptfooResult[];
  baselineHoldoutResults?: NormalizedPromptfooResult[];
  bestHoldoutResults?: NormalizedPromptfooResult[];
  governance: GovernanceAssessment;
  ledger: LedgerEntry[];
  originalPrompt: string;
  bestPrompt: string;
  finalVerdictLabel: string;
  finalVerdictReasons: string[];
  humanReviewRequired: boolean;
  runtimeStats?: {
    totalApiCalls?: number;
    totalLatencyMs?: number;
    cacheHits?: number;
    retryErrors?: number;
    errorCount?: number;
  };
  optimizeCalls?: number;
  optimizeCommand?: string;
  validationSplit?: number;
  // V6: Release state inputs
  publicBestPrompt?: string;
  releasePrompt?: string;
  releaseDecision?: ReleaseDecision;
}

export async function writeV5Report(input: V5ReportInput): Promise<void> {
  const lines: string[] = [];

  lines.push("# SkillFoo V5 \u8bc4\u6d4b\u4e0e\u6cbb\u7406\u62a5\u544a");
  lines.push("");

  // \u91cd\u8981\u58f0\u660e
  lines.push("## \u91cd\u8981\u58f0\u660e");
  lines.push("");
  lines.push("> **\u5206\u6570\u63d0\u5347 \u2260 \u771f\u5b9e\u4e1a\u52a1\u80fd\u529b\u5df2\u7ecf\u8bc1\u660e\u3002**");
  lines.push(">");
  lines.push("> **Promptfoo assertion \u901a\u8fc7 \u2260 \u4eba\u5de5\u786e\u8ba4\u4e1a\u52a1\u6b63\u786e\u3002**");
  lines.push(">");
  lines.push("> **\u540c\u6a21\u578b grader \u2260 \u72ec\u7acb\u5ba1\u67e5\u5b98\u3002**");
  lines.push(">");
  lines.push("> **\u81ea\u52a8\u751f\u6210\u6d4b\u8bd5 \u2260 \u6743\u5a01\u6d4b\u8bd5\u96c6\u3002**");
  lines.push("");

  // 1. \u8fd0\u884c\u914d\u7f6e\u548c Promptfoo \u7248\u672c
  lines.push("## 1. \u8fd0\u884c\u914d\u7f6e\u548c Promptfoo \u7248\u672c");
  lines.push("");
  lines.push("| \u914d\u7f6e\u9879 | \u503c |");
  lines.push("|---|---|");
  lines.push(`| \u9879\u76ee\u540d\u79f0 | ${input.projectName} |`);
  lines.push(`| Promptfoo \u7248\u672c | ${input.promptfooVersion} |`);
  lines.push("| \u6267\u884c\u4e0e\u8bc4\u6d4b\u5f15\u64ce | Promptfoo evaluate |");
  lines.push("| \u5019\u9009\u751f\u6210\u4e0e\u6cbb\u7406 | SkillFoo fixed loop |");
  lines.push(`| Promptfoo native optimize \u8c03\u7528\u6b21\u6570 | ${input.optimizeCalls ?? "\u672a\u8bb0\u5f55"} |`);
  if (input.optimizeCommand) {
    lines.push(`| \u4f18\u5316\u547d\u4ee4 | \`${input.optimizeCommand}\` |`);
  }
  if (input.validationSplit !== undefined) {
    lines.push(`| \u9a8c\u8bc1\u96c6\u6bd4\u4f8b | ${input.validationSplit} |`);
  }
  lines.push("");

  // 2. \u89d2\u8272\u914d\u7f6e\u548c\u6a21\u578b\u72ec\u7acb\u6027
  lines.push("## 2. \u89d2\u8272\u914d\u7f6e\u548c\u6a21\u578b\u72ec\u7acb\u6027");
  lines.push("");
  lines.push("| \u89d2\u8272 | \u6a21\u578b |");
  lines.push("|---|---|");
  lines.push(`| Target Provider | ${input.targetProviderModel} |`);
  lines.push(`| Grader Provider | ${input.graderProviderModel} |`);
  lines.push(`| Test Generator | ${input.testGeneratorSource} |`);
  lines.push("");
  if (input.sameModelGrader) {
    lines.push("**\u26a0\ufe0f \u8b66\u544a\uff1a\u540c\u6a21\u578b grader \u4e0d\u662f\u72ec\u7acb\u5ba1\u67e5\u5b98\u3002**");
    lines.push("");
  }
  if (input.hasAutoGeneratedTests) {
    lines.push("**\u26a0\ufe0f \u8b66\u544a\uff1a\u4f7f\u7528\u81ea\u52a8\u751f\u6210\u6d4b\u8bd5\uff0c\u4e0d\u7b49\u4e8e\u6743\u5a01\u6d4b\u8bd5\u96c6\u3002**");
    lines.push("");
  }

  // 3. Baseline \u4e0e Final \u5206\u6570\u5bf9\u6bd4
  lines.push("## 3. Baseline \u4e0e Final \u5206\u6570\u5bf9\u6bd4");
  lines.push("");
  const baselinePublicScore = input.governance.baselineMetrics.overallScore;
  const finalPublicScore = input.governance.candidateMetrics.overallScore;
  const publicDelta = input.governance.publicDelta;
  lines.push("| \u6307\u6807 | Baseline | Final | \u53d8\u5316 |");
  lines.push("|---|---:|---:|---:|");
  lines.push(`| Public \u603b\u5206 | ${baselinePublicScore.toFixed(1)} | ${finalPublicScore.toFixed(1)} | ${publicDelta >= 0 ? "+" : ""}${publicDelta.toFixed(1)} |`);
  if (input.governance.holdoutDelta !== null && input.baselineHoldoutResults && input.bestHoldoutResults) {
    const baselineHoldoutScore = summarizeMetricResults(input.baselineHoldoutResults).overallScore;
    const finalHoldoutScore = summarizeMetricResults(input.bestHoldoutResults).overallScore;
    lines.push(`| Holdout \u603b\u5206 | ${baselineHoldoutScore.toFixed(1)} | ${finalHoldoutScore.toFixed(1)} | ${input.governance.holdoutDelta >= 0 ? "+" : ""}${input.governance.holdoutDelta.toFixed(1)} |`);
  } else {
    lines.push("| Holdout \u603b\u5206 | \u672a\u6267\u884c | \u672a\u6267\u884c | N/A |");
  }
  lines.push(`| \u5173\u952e\u5b89\u5168\u65ad\u8a00\u5931\u8d25 | ${input.governance.baselineMetrics.criticalFailures} | ${input.governance.candidateMetrics.criticalFailures} | ${input.governance.criticalFailuresAfter > 0 ? "\u26a0\ufe0f \u6709\u5931\u8d25" : "\u65e0\u5931\u8d25"} |`);
  lines.push("");

  // 4. Promptfoo assertion \u7ef4\u5ea6\u5206\u6570
  lines.push("## 4. Promptfoo Assertion \u7ef4\u5ea6\u5206\u6570");
  lines.push("");
  lines.push("**Promptfoo score\uff1a\u7528\u4e8e\u7ed3\u679c\u6392\u5e8f\u548c\u62a5\u544a\u7edf\u8ba1\u3002**");
  lines.push("");
  lines.push("| \u7ef4\u5ea6 (Metric) | Baseline \u5206\u6570 | Final \u5206\u6570 |");
  lines.push("|---|---:|---:|");
  const allMetrics = new Set([
    ...Object.keys(input.governance.baselineMetrics.metricScores),
    ...Object.keys(input.governance.candidateMetrics.metricScores),
  ]);
  for (const metric of allMetrics) {
    const bScore = input.governance.baselineMetrics.metricScores[metric]?.toFixed(1) ?? "N/A";
    const fScore = input.governance.candidateMetrics.metricScores[metric]?.toFixed(1) ?? "N/A";
    lines.push(`| ${metric} | ${bScore} | ${fScore} |`);
  }
  lines.push("");

  // 5-7: Badcases and Regressions
  lines.push("## 5. \u771f\u5b9e\u4fee\u590d\u7684 Badcase");
  lines.push("");
  const fixedBadcases = findFixedBadcases(input.baselinePublicResults, input.bestPublicResults);
  if (fixedBadcases.length === 0) {
    lines.push("\u672c\u6b21\u8fd0\u884c\u672a\u68c0\u6d4b\u5230\u771f\u5b9e\u4fee\u590d\u7684 badcase\u3002");
  } else {
    lines.push("| Test ID | \u4fee\u590d\u524d\u5206\u6570 | \u4fee\u590d\u540e\u5206\u6570 | \u4fee\u590d\u8bf4\u660e |");
    lines.push("|---|---:|---:|---|");
    for (const bc of fixedBadcases) {
      lines.push(`| ${bc.testId} | ${bc.beforeScore.toFixed(0)} | ${bc.afterScore.toFixed(0)} | ${bc.explanation} |`);
    }
  }
  lines.push("");

  lines.push("## 6. \u4ecd\u672a\u4fee\u590d\u7684 Badcase");
  lines.push("");
  const unfixedBadcases = input.bestPublicResults.filter((r) => !r.pass);
  if (unfixedBadcases.length === 0) {
    lines.push("\u65e0\u672a\u4fee\u590d\u7684 badcase\u3002");
  } else {
    lines.push("| Test ID | \u5206\u6570 | \u5931\u8d25\u539f\u56e0 |");
    lines.push("|---|---:|---|");
    for (const bc of unfixedBadcases) {
      const failed = bc.assertions.filter((a) => !a.pass);
      const reason = failed.length > 0 ? failed.map((a) => a.reason).join("; ") : "\u672a\u77e5\u539f\u56e0";
      lines.push(`| ${bc.testId} | ${bc.score.toFixed(0)} | ${reason} |`);
    }
  }
  lines.push("");

  lines.push("## 7. \u65b0\u589e Regressions");
  lines.push("");
  const regressions = findRegressions(input.baselinePublicResults, input.bestPublicResults);
  if (regressions.length === 0) {
    lines.push("\u65e0\u65b0\u589e\u56de\u5f52\u3002");
  } else {
    lines.push("| Test ID | \u4fee\u590d\u524d\u5206\u6570 | \u4fee\u590d\u540e\u5206\u6570 | \u4e0b\u964d\u5e45\u5ea6 |");
    lines.push("|---|---:|---:|---:|");
    for (const reg of regressions) {
      lines.push(`| ${reg.testId} | ${reg.beforeScore.toFixed(0)} | ${reg.afterScore.toFixed(0)} | ${(reg.beforeScore - reg.afterScore).toFixed(0)} |`);
    }
  }
  lines.push("");

  // 8. Prompt diff
  lines.push("## 8. Prompt Diff");
  lines.push("");
  lines.push("**\u6700\u7ec8\u5b89\u5168\u7ed3\u8bba\u4ec5\u9488\u5bf9\u6700\u7ec8 kept Prompt\uff0c\u4e0d\u9488\u5bf9\u5df2\u6dd8\u6c70\u5019\u9009\u3002**");
  lines.push("");
  lines.push("### \u539f\u59cb Prompt");
  lines.push("");
  lines.push("```text");
  lines.push(input.originalPrompt);
  lines.push("```");
  lines.push("");
  lines.push("### Release Prompt");
  lines.push("");
  lines.push("```text");
  lines.push(input.releasePrompt ?? input.bestPrompt);
  lines.push("```");
  lines.push("");
  // V6: Public Best Candidate (evidence only)
  if (input.publicBestPrompt && input.publicBestPrompt !== (input.releasePrompt ?? input.bestPrompt)) {
    lines.push("### Public Best Candidate (Evidence Only)");
    lines.push("");
    lines.push("This candidate passed the public keep gate but was not released.");
    lines.push("");
    lines.push("```text");
    lines.push(input.publicBestPrompt);
    lines.push("```");
    lines.push("");
  }
  lines.push("### \u65b0\u589e\u884c");
  lines.push("");
  const addedLines = input.governance.promptChange.addedLines;
  if (addedLines.length === 0) {
    lines.push("\u65e0\u65b0\u589e\u884c\u3002");
  } else {
    for (const line of addedLines) { lines.push(`+ ${line}`); }
  }
  lines.push("");
  lines.push("### \u5220\u9664\u884c");
  lines.push("");
  const removedLines = input.governance.promptChange.removedLines;
  if (removedLines.length === 0) {
    lines.push("\u65e0\u5220\u9664\u884c\u3002");
  } else {
    for (const line of removedLines) { lines.push(`- ${line}`); }
  }
  lines.push("");

  // 9. Scope bloat and over-refusal
  lines.push("## 9. Scope Bloat \u548c Over-Refusal \u5ba1\u67e5\u7ed3\u679c");
  lines.push("");
  lines.push("**SkillFoo governance\uff1a\u51b3\u5b9a\u662f\u5426\u5141\u8bb8 keep \u548c\u6700\u7ec8 verdict\u3002**");
  lines.push("");
  lines.push("| \u68c0\u67e5\u9879 | \u6570\u91cf |");
  lines.push("|---|---:|");
  lines.push(`| Scope bloat\uff08\u603b\u8ba1\uff09 | ${input.governance.promptChange.scopeBloatCount} |`);
  lines.push(`| Scope bloat\uff08\u4e25\u91cd\uff09 | ${input.governance.promptChange.severeScopeBloatCount} |`);
  lines.push(`| Over-refusal\uff08\u603b\u8ba1\uff09 | ${input.governance.promptChange.overRefusalCount} |`);
  lines.push(`| Over-refusal\uff08\u4e25\u91cd\uff09 | ${input.governance.promptChange.severeOverRefusalCount} |`);
  lines.push("");
  if (input.governance.promptChange.notes.length > 0) {
    lines.push("### \u8be6\u7ec6\u8bf4\u660e");
    lines.push("");
    for (const note of input.governance.promptChange.notes) { lines.push(`- ${note}`); }
    lines.push("");
  }

  // 10. Runtime stats
  lines.push("## 10. \u8fd0\u884c\u65f6\u7edf\u8ba1");
  lines.push("");
  if (input.runtimeStats) {
    lines.push("| \u7edf\u8ba1\u9879 | \u503c |");
    lines.push("|---|---:|");
    lines.push(`| API \u8c03\u7528\u6570 | ${input.runtimeStats.totalApiCalls ?? "\u672a\u8bb0\u5f55"} |`);
    lines.push(`| \u603b\u8017\u65f6 | ${input.runtimeStats.totalLatencyMs ? (input.runtimeStats.totalLatencyMs / 1000).toFixed(1) + "s" : "\u672a\u8bb0\u5f55"} |`);
    lines.push(`| \u7f13\u5b58\u547d\u4e2d | ${input.runtimeStats.cacheHits ?? "\u672a\u8bb0\u5f55"} |`);
    lines.push(`| \u9519\u8bef\u91cd\u8bd5 | ${input.runtimeStats.retryErrors ?? "\u672a\u8bb0\u5f55"} |`);
    lines.push(`| \u9519\u8bef\u6570 | ${input.runtimeStats.errorCount ?? "\u672a\u8bb0\u5f55"} |`);
  } else {
    lines.push("\u8fd0\u884c\u65f6\u7edf\u8ba1\u672a\u8bb0\u5f55\u3002");
  }
  lines.push("");

  // 11. Keep/rollback ledger
  lines.push("## 11. Keep/Rollback \u8d26\u672c");
  lines.push("");
  lines.push("| Iteration | Engine | Prompt Version | Status | Score | Pass Rate | Evidence |");
  lines.push("|---:|---|---|---|---:|---:|---|");
  for (const entry of input.ledger) {
    lines.push(`| ${entry.iteration} | Promptfoo | ${entry.promptVersion} | ${entry.status} | ${entry.score.toFixed(1)} | ${(entry.passRate * 100).toFixed(0)}% | ${entry.summary} |`);
  }
  lines.push("");

  // 12. Final verdict
  lines.push("## 12. Final Verdict \u548c\u4eba\u5de5\u590d\u6838\u5efa\u8bae");
  lines.push("");
  lines.push("| \u9879\u76ee | \u503c |");
  lines.push("|---|---|");
  lines.push(`| Verdict | ${input.finalVerdictLabel} |`);
  lines.push(`| \u9700\u8981\u4eba\u5de5\u590d\u6838 | ${input.humanReviewRequired ? "\u662f" : "\u5426"} |`);
  lines.push("");
  if (input.finalVerdictReasons.length > 0) {
    lines.push("### \u5224\u5b9a\u539f\u56e0");
    lines.push("");
    for (const reason of input.finalVerdictReasons) { lines.push(`- ${reason}`); }
    lines.push("");
  }
  if (input.humanReviewRequired) {
    lines.push("### \u4eba\u5de5\u590d\u6838\u5efa\u8bae");
    lines.push("");
    lines.push("1. \u68c0\u67e5 target \u548c grader \u662f\u5426\u4f7f\u7528\u76f8\u540c\u6a21\u578b\u3002");
    lines.push("2. \u68c0\u67e5\u81ea\u52a8\u751f\u6210\u6d4b\u8bd5\u662f\u5426\u8986\u76d6\u4e1a\u52a1\u5173\u952e\u573a\u666f\u3002");
    lines.push("3. \u68c0\u67e5 holdout \u662f\u5426\u6709\u4e0b\u964d\u3002");
    lines.push("4. \u68c0\u67e5 scope bloat \u548c over-refusal \u662f\u5426\u5f71\u54cd\u4e1a\u52a1\u80fd\u529b\u3002");
    lines.push("5. \u5206\u6570\u63d0\u5347\u4e0d\u7b49\u4e8e\u771f\u5b9e\u4e1a\u52a1\u80fd\u529b\u5df2\u7ecf\u8bc1\u660e\u3002");
    lines.push("");
  }

  // V6: Release Decision
  if (input.releaseDecision) {
    lines.push("## 13. Release Decision");
    lines.push("");
    lines.push("| Field | Value |");
    lines.push("|---|---|");
    lines.push("| Status | " + input.releaseDecision.status + " |");
    lines.push("| Released Prompt Version | " + input.releaseDecision.releasedPromptVersion + " |");
    if (input.releaseDecision.reasons.length > 0) {
      lines.push("| Reasons | " + input.releaseDecision.reasons.join(", ") + " |");
    }
    if (input.releaseDecision.holdoutDelta !== undefined) {
      lines.push("| Holdout Delta | " + input.releaseDecision.holdoutDelta.toFixed(1) + " |");
    }
    lines.push("");
  }

  // V6: PromptSpec (Advisory)
  lines.push("## 15. PromptSpec (Advisory)");
  lines.push("");
  lines.push("PromptSpec v1 assessment is advisory only. It does not affect candidate scoring or release decisions.");
  lines.push("");
  lines.push("See prompt-spec-assessment.json for structural analysis of baseline, public best, and release prompt.");
  lines.push("");

  await writeFile(join(input.runDir, "v5-report.md"), lines.join("\n"), "utf-8");
}

function findFixedBadcases(baseline: NormalizedPromptfooResult[], final: NormalizedPromptfooResult[]) {
  const baselineMap = new Map(baseline.map((r) => [r.testId, r]));
  const fixed: Array<{ testId: string; beforeScore: number; afterScore: number; explanation: string }> = [];
  for (const finalResult of final) {
    const baselineResult = baselineMap.get(finalResult.testId);
    if (!baselineResult) continue;
    if (!baselineResult.pass && finalResult.pass) {
      fixed.push({ testId: finalResult.testId, beforeScore: baselineResult.score, afterScore: finalResult.score, explanation: `\u5206\u6570\u4ece ${baselineResult.score.toFixed(0)} \u63d0\u5347\u81f3 ${finalResult.score.toFixed(0)}` });
    }
  }
  return fixed;
}

function findRegressions(baseline: NormalizedPromptfooResult[], final: NormalizedPromptfooResult[]) {
  const baselineMap = new Map(baseline.map((r) => [r.testId, r]));
  const regressions: Array<{ testId: string; beforeScore: number; afterScore: number }> = [];
  for (const finalResult of final) {
    const baselineResult = baselineMap.get(finalResult.testId);
    if (!baselineResult) continue;
    if (finalResult.score < baselineResult.score) {
      regressions.push({ testId: finalResult.testId, beforeScore: baselineResult.score, afterScore: finalResult.score });
    }
  }
  return regressions;
}
