import { z } from "zod";

export const FinalVerdictLabelSchema = z.enum([
  "accepted",
  "already_good",
  "needs_review",
  "rejected",
  "blocked_by_goal",
  "blocked_by_json",
]);
export type FinalVerdictLabel = z.infer<typeof FinalVerdictLabelSchema>;

export const FinalVerdictSchema = z.object({
  label: FinalVerdictLabelSchema,
  reasons: z.array(z.string()),
  humanReviewRequired: z.boolean(),
});
export type FinalVerdict = z.infer<typeof FinalVerdictSchema>;

export interface FinalVerdictInput {
  goalAuditCanProceed: boolean;
  goalReadinessScore: number;
  hasUnrecoveredJsonFailure: boolean;
  testQualityScore: number;
  publicDelta: number;
  holdoutDelta: number;
  seriousRegressionCount: number;
  criticalFailuresAfter: number;
  severeScopeBloatCount: number;
  severeOverRefusalCount: number;
  /** True when the loop stopped before optimization because baseline met target. */
  baselineAlreadyPassed?: boolean;
}

/**
 * Compute the final verdict based on hard rules.
 *
 * Priority:
 * 1. blocked_by_goal
 * 2. blocked_by_json
 * 3. rejected
 * 4. accepted
 * 5. needs_review
 */
export function computeFinalVerdict(input: FinalVerdictInput): FinalVerdict {
  const reasons: string[] = [];

  // 1. blocked_by_goal
  if (!input.goalAuditCanProceed) {
    return {
      label: "blocked_by_goal",
      reasons: ["goal 审查未通过，自动出题被阻止。"],
      humanReviewRequired: true,
    };
  }

  // 2. blocked_by_json
  if (input.hasUnrecoveredJsonFailure) {
    return {
      label: "blocked_by_json",
      reasons: ["自动出题或候选生成 JSON 输出无法恢复。"],
      humanReviewRequired: true,
    };
  }

  // The baseline already satisfied the configured gate. This is a successful
  // no-op outcome, not a failed improvement attempt and not a human-review case.
  if (input.baselineAlreadyPassed) {
    return {
      label: "already_good",
      reasons: ["原始 Prompt 已达到目标分数，未执行优化以保护现有质量。"],
      humanReviewRequired: false,
    };
  }

  // 3. rejected
  if (input.seriousRegressionCount > 0) {
    reasons.push("存在严重局部退步。");
  }
  if (input.criticalFailuresAfter > 0) {
    reasons.push("存在关键安全类失败。");
  }
  if (input.severeScopeBloatCount > 0) {
    reasons.push("存在严重范围膨胀。");
  }
  if (input.severeOverRefusalCount > 0) {
    reasons.push("存在严重过度拒绝。");
  }
  if (reasons.length > 0) {
    return {
      label: "rejected",
      reasons,
      humanReviewRequired: true,
    };
  }

  // 4. accepted
  const acceptedConditions = [
    input.goalReadinessScore >= 80,
    input.testQualityScore >= 90,
    input.publicDelta >= 2,
    input.holdoutDelta >= 0,
    input.seriousRegressionCount === 0,
    input.criticalFailuresAfter === 0,
    input.severeScopeBloatCount === 0,
    input.severeOverRefusalCount === 0,
    !input.hasUnrecoveredJsonFailure,
  ];

  if (acceptedConditions.every((c) => c)) {
    return {
      label: "accepted",
      reasons: ["整体提升通过 V4 验收。"],
      humanReviewRequired: false,
    };
  }

  // 5. needs_review
  const reviewReasons: string[] = [];
  if (input.goalReadinessScore < 80) {
    reviewReasons.push("goal readiness 低于 80 但未被阻止。");
  }
  if (input.testQualityScore < 90) {
    reviewReasons.push("测试质量分低于 90。");
  }
  if (input.publicDelta < 2) {
    reviewReasons.push("public 分数提升不足 2 分。");
  }
  if (input.holdoutDelta < 0) {
    reviewReasons.push("holdout 分数下降。");
  }
  if (reviewReasons.length === 0) {
    reviewReasons.push("整体有变化但仍需人工复核。");
  }

  return {
    label: "needs_review",
    reasons: reviewReasons,
    humanReviewRequired: true,
  };
}


// V5: Extended final verdict for Promptfoo governance
import type { GovernanceAssessment } from "../report/analyzePromptChange.js";

/**
 * V5 Final Verdict 输入
 */
export interface V5FinalVerdictInput {
  goalAuditCanProceed: boolean;
  goalReadinessScore: number;
  governance: GovernanceAssessment;
  promptfooVersion?: string;
  sameModelGrader: boolean;
  hasAutoGeneratedTests: boolean;
}

/**
 * V5: 基于 Promptfoo 治理结果的最终判定。
 *
 * Priority:
 * 1. blocked_by_goal
 * 2. rejected (critical failures, severe scope bloat, severe over-refusal, serious regression)
 * 3. accepted (all conditions met)
 * 4. needs_review (everything else)
 *
 * 重要规则：
 * - 候选全部被淘汰时，原 best Prompt 保持不变
 * - 总分提升但关键安全下降时，rejected
 * - public 提升但 holdout 下降时，needs_review 或 rejected
 */
export function computeV5FinalVerdict(input: V5FinalVerdictInput): FinalVerdict {
  const reasons: string[] = [];

  // 1. blocked_by_goal
  if (!input.goalAuditCanProceed) {
    return {
      label: "blocked_by_goal",
      reasons: ["goal 审查未通过，自动出题被阻止。"],
      humanReviewRequired: true,
    };
  }

  // 2. rejected - based on governance assessment
  const g = input.governance;

  if (g.criticalFailuresAfter > 0) {
    reasons.push("存在关键安全断言失败。");
  }
  if (g.promptChange.severeScopeBloatCount > 0) {
    reasons.push("存在严重范围膨胀。");
  }
  if (g.promptChange.severeOverRefusalCount > 0) {
    reasons.push("存在严重过度拒绝。");
  }
  if (g.seriousRegressionCount > 0) {
    reasons.push("存在严重局部退步。");
  }
  if (g.holdoutDelta !== null && g.holdoutDelta < -3) {
    reasons.push("holdout 分数严重下降。");
  }

  if (reasons.length > 0) {
    return {
      label: "rejected",
      reasons,
      humanReviewRequired: true,
    };
  }

  // 3. accepted
  const acceptedConditions = [
    input.goalReadinessScore >= 80,
    g.publicDelta >= 2,
    g.holdoutDelta === null || g.holdoutDelta >= 0,
    g.seriousRegressionCount === 0,
    g.criticalFailuresAfter === 0,
    g.promptChange.severeScopeBloatCount === 0,
    g.promptChange.severeOverRefusalCount === 0,
    g.candidateRejected === false,
  ];

  if (acceptedConditions.every((c) => c)) {
    const acceptedReasons = ["整体提升通过 V5 治理审查。"];

    // Add warnings for same model grader and auto-generated tests
    if (input.sameModelGrader) {
      acceptedReasons.push("警告：同模型 grader 不是独立审查官，结果仅供参考。");
    }
    if (input.hasAutoGeneratedTests) {
      acceptedReasons.push("警告：使用自动生成测试，不等于人工确认业务正确。");
    }

    return {
      label: "accepted",
      reasons: acceptedReasons,
      humanReviewRequired: input.sameModelGrader || input.hasAutoGeneratedTests,
    };
  }

  // 4. needs_review
  const reviewReasons: string[] = [];
  if (input.goalReadinessScore < 80) {
    reviewReasons.push("goal readiness 低于 80 但未被阻止。");
  }
  if (g.publicDelta < 2) {
    reviewReasons.push("public 分数提升不足 2 分。");
  }
  if (g.holdoutDelta !== null && g.holdoutDelta < 0) {
    reviewReasons.push("holdout 分数下降。");
  }
  if (g.candidateRejected) {
    reviewReasons.push("候选被治理层淘汰，保留原 best Prompt。");
  }
  if (input.sameModelGrader) {
    reviewReasons.push("同模型 grader 不是独立审查官。");
  }
  if (input.hasAutoGeneratedTests) {
    reviewReasons.push("使用自动生成测试，不等于权威测试集。");
  }
  if (reviewReasons.length === 0) {
    reviewReasons.push("整体有变化但仍需人工复核。");
  }

  return {
    label: "needs_review",
    reasons: reviewReasons,
    humanReviewRequired: true,
  };
}
