import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { ImprovementAssessment } from "./assessImprovement.js";

export async function writeSupervisorReport(
  runDir: string,
  assessment: ImprovementAssessment
): Promise<void> {
  await writeFile(
    join(runDir, "improvement-assessment.json"),
    JSON.stringify(assessment, null, 2),
    "utf-8"
  );

  let report = "# Supervisor Improvement Report\n\n";
  report += "## Verdict\n\n";
  report += `Improvement label: ${assessment.label}\n\n`;
  report += "## Quantitative Metrics\n\n";
  report += "| Metric | Value |\n|---|---:|\n";
  report += `| Public delta | ${assessment.publicDelta.toFixed(1)} |\n`;
  report += `| Holdout delta | ${assessment.holdoutDelta === null ? "NA" : assessment.holdoutDelta.toFixed(1)} |\n`;
  report += `| Public-holdout gap | ${assessment.publicHoldoutGap === null ? "NA" : assessment.publicHoldoutGap.toFixed(1)} |\n`;
  report += `| Regression count | ${assessment.regressionCount} |\n`;
  report += `| Serious regression count | ${assessment.seriousRegressionCount} |\n`;
  report += `| Critical failures after | ${assessment.criticalFailuresAfter} |\n`;
  report += `| Low-score cases after | ${assessment.lowScoreAfter} |\n`;
  report += `| Min score before | ${assessment.minScoreBefore.toFixed(1)} |\n`;
  report += `| Min score after | ${assessment.minScoreAfter.toFixed(1)} |\n`;
  report += "\n## Rule Explanation\n\n";
  report += `${assessment.explanation}\n\n`;
  report += "## Boundary\n\n";
  report += "This verdict is generated by deterministic code metrics. LLM explanations may be added later, but they must not override this label.\n";

  await writeFile(join(runDir, "supervisor-report.md"), report, "utf-8");
}
